# file: docker-compose.yml v1.0
services:
  fakesite:
    image: nginx:alpine
    container_name: fakesite
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/index.html:/usr/share/nginx/html/index.html:ro
      - ./data/status.php:/usr/share/nginx/html/status.php:ro
      - ./data/phpinfo.php:/usr/share/nginx/html/phpinfo.php:ro
      - ./data/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
      - ./data/apple-touch-icon.png:/usr/share/nginx/html/apple-touch-icon.png:ro
      - ./data/robots.txt:/usr/share/nginx/html/robots.txt:ro
      - ./data/VERSION:/usr/share/nginx/html/VERSION:ro
      - /var/www/acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/YOUDOMEN.XXX/fullchain.pem:/etc/nginx/certs/fakesite.crt:ro
      - /etc/letsencrypt/live/YOUDOMEN.XXX/privkey.pem:/etc/nginx/certs/fakesite.key:ro
    networks:
      - fakesite
    depends_on:
      - php-fpm
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M

  php-fpm:
    image: php:8.3-fpm-alpine
    container_name: fakesite-php
    restart: unless-stopped
    volumes:
      - ./data/status.php:/usr/share/nginx/html/status.php:ro
      - ./data/phpinfo.php:/usr/share/nginx/html/phpinfo.php:ro
    networks:
      - fakesite
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 32M

networks:
  fakesite:
    driver: bridge
